# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_serv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_serv.proto',
  package='chat',
  syntax='proto3',
  serialized_pb=_b('\n\x0fgrpc_serv.proto\x12\x04\x63hat\"\"\n\x0fTransmitMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x04\x43hat\x12\x36\n\x04Send\x12\x15.chat.TransmitMessage\x1a\x15.chat.TransmitMessage\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRANSMITMESSAGE = _descriptor.Descriptor(
  name='TransmitMessage',
  full_name='chat.TransmitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='chat.TransmitMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['TransmitMessage'] = _TRANSMITMESSAGE

TransmitMessage = _reflection.GeneratedProtocolMessageType('TransmitMessage', (_message.Message,), dict(
  DESCRIPTOR = _TRANSMITMESSAGE,
  __module__ = 'grpc_serv_pb2'
  # @@protoc_insertion_point(class_scope:chat.TransmitMessage)
  ))
_sym_db.RegisterMessage(TransmitMessage)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class ChatStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/chat.Chat/Send',
        request_serializer=TransmitMessage.SerializeToString,
        response_deserializer=TransmitMessage.FromString,
        )


class ChatServicer(object):

  def Send(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=TransmitMessage.FromString,
          response_serializer=TransmitMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chat.Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaChatServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def Send(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaChatStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def Send(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Send.future = None


def beta_create_Chat_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('chat.Chat', 'Send'): TransmitMessage.FromString,
  }
  response_serializers = {
    ('chat.Chat', 'Send'): TransmitMessage.SerializeToString,
  }
  method_implementations = {
    ('chat.Chat', 'Send'): face_utilities.unary_unary_inline(servicer.Send),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_Chat_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('chat.Chat', 'Send'): TransmitMessage.SerializeToString,
  }
  response_deserializers = {
    ('chat.Chat', 'Send'): TransmitMessage.FromString,
  }
  cardinalities = {
    'Send': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'chat.Chat', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
