__all__ = ['command_assign',
           'command_cat',
           'command_echo',
           'command_exit',
           'command_grep',
           'command_pipe',
           'command_pwd',
           'command_wc',
           'command_cd',
           'command_ls']